### ISSUE TITLE
NLP

### ISSUE THREAD

**Issue by castellanosr** [Edurate/edurate#10]
Detect for repeated phrases or specific things (eg compiling, building, javadoc). Set key words such as "too fast," or "don't understand". We can use sentiment analysis as well. We should look at LAD in order to implement no human involvement and look at pyLADvis.

**Comment by dillam** [comment]
I want this issue

**Comment by dillam** [comment]
Zach Cole also wants this issue

**Comment by castellanosr** [comment]
Detect for repeated phrases or specific things (eg compiling, building, javadoc). Set key words such as "too fast," or "don't understand". We can use sentiment analysis as well. We should look at LAD in order to implement no human involvement and look at pyLADvis.

**Comment by toccinAC** [comment]
Hey, this is the website that I found for Gensim. 
[https://radimrehurek.com/gensim/index.html](url)

**Comment by JattMones** [comment]
Hey everyone. Just an update, I was able to download and install Gensim earlier this week, but when I ran the installation test, it failed due to problems with a feature called Tensorflow. However, after talking to Kapfhammer today, we should not have to use anything that depends on Tensorflow in this lab. In Kapfhammers SEED repository, he has the "seed_gensim" file which contains methods for creating a topic model, creating a topic model dictionary, and showing topic model textually. We should definitely focus on implementing similar methods to these, and also try to narrow down how we want to analyze our data using Gensim. Here is a list of some features I think might be useful:                  
-gensim.corpora.wikicorpus (Will allow us to see the frequency of words, along with other features)           -gensim.similarities, gensim.corpora & gensim.models (allows us to find a similarity percentage/ correlation between different texts, along with other features)

**Comment by JattMones** [comment]
Please comment if you think a particular feature would work better than one of the ones I suggested, or if there are additional features that would be helpful to our project. Since we need a working demo of the whole Edurate system by 2:30 Tuesday, Kapfhammer suggested we have our NLP implementation done ASAP. I would say Sunday night should be the latest this is completed, so that there is at least one full day that other groups have time to integrate our systems. I will be gone Friday following class until sometime Saturday afternoon. If we could meet Sunday, and at least a little while Saturday afternoon, there's a chance that we'll have a basic working system by the deadline.

**Comment by burrowss** [comment]
I agree. We need to have the NLP and the other important parts of the system done by Sunday. A meeting then would be good too. I think the features you were suggesting should be what we use so if you guys on this issue could figure out how we can get that stuff working, it would be great.

**Comment by IzaakMiller** [comment]
![screenshot from 2017-10-29 20-25-35](https://user-images.githubusercontent.com/19733927/32150294-7e13257a-bce7-11e7-81d6-ba9c5b1ad1bc.png)
Here is some NLP code. Is this something that we could use or does it have to be from a different package?

**Comment by IzaakMiller** [comment]
import nltk.sentiment.* is what should be the import statement. Missing the *.

**Comment by IzaakMiller** [comment]
Whoops: It's actually "from nltk.sentiment.vader import SentimentIntensityAnalyzer"

**Comment by IzaakMiller** [comment]
Do we have to use gensim or was that a suggestion?

**Comment by toccinAC** [comment]
We have to.

**Comment by mariakimheinert** [comment]
Closing because gensim has been integrated.
