### ISSUE TITLE
Create graphical output(Graphs and stuff)

### ISSUE THREAD

**Issue by dillam** [Edurate/edurate#13]
For this two-week period Kapfhammer said we should just be able to run the program in the terminal and print out averages of the professors' scores. We do not graphs yet, but they should be added eventually. The program must be able to remember responses so that we can see progress - dump information into the same spreadsheet, but use time stamps.

**Comment by castellanosr** [comment]
For this two-week period Kapfhammer said we should just be able to run the program in the terminal and print out averages of the professors' scores. We do not graphs yet, but they should be added eventually. The program must be able to remember responses so that we can see progress - dump information into the same spreadsheet, but use time stamps.

**Comment by dillam** [comment]
The csv file will have an output similar to this.

```
"10/23/17","dillam","Answer to textual question","1","3","2"
```

**Comment by bristola** [comment]
The code for this issue requires ggplot and pandas.  Requirements for the system must be added at some point so that users `pip install ggplot` and `pip install pandas` if they are not already installed.  Also, I committed my code for *graph1* which displays a line graph of average scores as time goes on.

**Comment by cookc3174** [comment]
I think I was working on the same program as you Austin. I tried pulling what you had just committed but it won't let me. Do you know how to fix this?

**Comment by bristola** [comment]
What is the git error message that you are receiving?

**Comment by cookc3174** [comment]
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by cookc3174** [comment]
I think because we were working on it the same time it created a merge conflict

**Comment by bristola** [comment]
try to do a `git pull origin i-13-graphs`.  And then try and push.
If that doesn't work, you could try and do a `git stash`, then `git pull`, then `git stash pop`.  After that you could do a `git push`.  If you try the second way, it may be a good idea to save a backup of your work in a different file beforehand just in case.

**Comment by cookc3174** [comment]
I think I need to go through and delete the lines of code I added. I tried all of those things and it keeps saying that we need to fix issues within the program so that it can properly merge.

**Comment by bristola** [comment]
As long as nothing else is changed except your function then it should work. So try and get your code to only have changes in your function.

**Comment by cookc3174** [comment]
I think I fixed the problem. Now what does the "Change over Time" graph suppose to represent?

**Comment by bristola** [comment]
Ignore that one, I did that one already but accidentally listed it twice in the functions.

**Comment by bristola** [comment]
I'd say we would need a bar graph which is just the average scores for each question for the most recent week.

**Comment by cookc3174** [comment]
how did you run and test the program to see what the graphs looked liked?

**Comment by bristola** [comment]
In the *graph* function, set a variable like g2 equal to what is returned from you function with the data_frame variable passed in.  Then just `print(g2)`.  You can look at my code on how I did it.

**Comment by cookc3174** [comment]
For some reason when I try running the program for the graphs it gives me this error
`cookc@x2go:~/cs280F2017/edurate/edurate$ python graphing.py
Traceback (most recent call last):
  File "graphing.py", line 8, in <module>
    from ggplot import *
ImportError: No module named ggplot
`

**Comment by cookc3174** [comment]
I added some code to graph 2 and found out how to create a time interval using pandas. Graph 2 still needs other implementations. It's really hard to create this graph because I am unable to run the program and test it. Austin what time can you meet this weekend to discuss graph 2 and the other issue we are on?

**Comment by bristola** [comment]
You are getting that error because you either didn't `pip install ggplot` or you are not running the program with `python3 graphing.py` because it requires python version 3.  If those two don't work, try installing ggplot again using `pip3 install ggplot` rather than just `pip install ggplot`. 
Also, I already created the time intervals graph in the function *graph1*.  You should create a bar graph for the average scores just using scores from the most recent week recorded. I can meet anytime today.

**Comment by cookc3174** [comment]
Ok ill try that. When and where can you meet later this evening.

**Comment by bristola** [comment]
It would probably be better for me to meet tomorrow.  Do you have anything that needs to be helped with right now?

**Comment by cookc3174** [comment]
The only thing I really need help on is probably just getting the average scores. I'm kind of confused on that part.

**Comment by bristola** [comment]
Check line 53 in the code right now.  That's how I took averages, however, since you should have filtered the data so that only the most recent date is left in the dataset, you should only groupby Question rather than Date and Question.  We can meet tomorrow to fix it all and do the other task.

**Comment by cookc3174** [comment]
alright sounds good.

**Comment by bristola** [comment]
When do you want to meet at alden today @cookc3174

**Comment by cookc3174** [comment]
Can you do 4?

**Comment by bristola** [comment]
Yes
