### ISSUE TITLE
Create Google Form

### ISSUE THREAD

**Issue by dillam** [Edurate/edurate#15]

**Comment by castellanosr** [comment]
I have received example questionnaires from JJ, OBC, and Kapfhammer that we can review and select questions from. Kapfhammer said we should have a mix of open ended questions as well as number based ones. Kapfhammer said that, at minimum, we should have the number based questions.He mentioned that the questionnaire should not be too long because if is is students will not provide helpful answers. We should also phrase the questions in such a way that "yes," "no," "good," etc do not work.

**Comment by castellanosr** [comment]
Some examples Kapfhammer mentioned during our interview were labs vs lecture, homework vs tests, what's working well/is helpful, what needs work/would help you better, what was most confusing about your most recent ______.

**Comment by castellanosr** [comment]
@millinj2 and I completed the questionnaire. https://goo.gl/forms/0izd9oA9xmD9NDQA2
